resources:
  - name: MyGitHub
    type: GitRepo
    configuration:
      gitProvider: sanjanrahman_github   # replace with your integration  
      path: sanjanrahman/jfrog-pipelines-hello-world    # replace with your repository name
      branches:
        include: master
        
pipelines:
  - name: pipeline-hello-world
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo
        execution:
          onExecute:
            - printenv
            - echo $res_myAppRepo_commitSha
            - add_run_variables first_stepid=$step_id

      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "Hello world"
            - echo $first_stepid

      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - echo "Hello world"
            - echo $first_stepid
